---
name: cicd workflow to create docker image and upload image into DockerHub
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: "11"
      - name: Build with Maven
        run: mvn clean install
      - name: Login to DockerHUB
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mydimages:latest .
      - name: Push docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mydimages:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH to Docker Host and Deploy Container
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DOCKER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{secrets.SSH_PASSWORD }}
          script: >
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mydimages:latest

            sudo docker stop myjavaapp || true

            sudo docker rm myjavaapp || true

            sudo docker run -d --name myjavaapp -p8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/mydimages:latest
