name: Build and Deploy Java Project

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload WAR file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-app-war
        path: target/*.war

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download WAR file artifact
      uses: actions/download-artifact@v4
      with:
        name: my-app-war
        path: ./deploy

    - name: Deploy to Tomcat
      run: |
        curl --upload-file ./deploy/*.war "http://${{ secrets.TOMCAT_SERVER_URL }}:${{ secrets.TOMCAT_PORT }}/manager/text/deploy?path=/myapp&update=true" --user "${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}"
      env:
        TOMCAT_SERVER_URL: ${{ secrets.TOMCAT_SERVER_URL }}
        TOMCAT_PORT: ${{ secrets.TOMCAT_PORT }}
        TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
        TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
